import * as element from './elements.js'
import send from './net.js'

/*LOAD MENU*/

const page = window.location.pathname;

if(page.includes("customer")){
	draw_customer_menu();
}else if(page.includes("sales_orders")){
	draw_sales_order_menu();
}

function erase_main_menu(){
	var btn = document.getElementById("sales_order_menu");
	var btn2 = document.getElementById("customer_menu");
	btn.remove();
	btn2.remove();
}

function draw_customer_menu(){

	var new_customer = document.getElementById("new-cust");
	var edit_customer = document.getElementById("edit-cust");
	
	new_customer.addEventListener("click",render_new_customer);
	edit_customer.addEventListener("click",render_edit_cusromer);
}

function draw_sales_order_menu(){

	var insert_new_order = document.getElementById("new-order");
	var edit_order = document.getElementById("edit-order");

	insert_new_order.addEventListener("click",render_new_order);
	edit_order.addEventListener("click",render_edit_order);
}


function create_table(row,column_name,id_value){
	var table  = document.createElement("table");
	var t_body = document.createElement("tbody");
	for(let i = 0; i < 2; i++){
		var r = document.createElement("tr");
		/* table header */
		if(i == 0){
			for(let j = 0; j < column_name.length; j++){
				var cell = document.createElement("th");		
				cell.textContent = `${column_name[j]}`;
				cell.setAttribute("width","200");
				cell.setAttribute("style","font-size:27px;text-align:center;");
				r.appendChild(cell);
			}
		}else{
			for(let k = 0; k < column_name.length;k++){
				var cell = document.createElement("td");		
				cell.setAttribute("width","200");
				cell.setAttribute("style","padding:0;");

				if(column_name[k] === "Total"){
					var tot = document.createElement("label");				
					tot.setAttribute("style","width:100%;height:100%;box-sizing:border-box;font-size:24px;");
					tot.classList.add(".tot");
					cell.appendChild(tot);
					r.appendChild(cell);
				}else if(column_name[k] === "Qty"){
					var input = document.createElement("input");
					input.setAttribute("min",0);
					input.classList.add(".qty","input_no_border");
					input.value = 0.00;

					cell.appendChild(input);
					r.appendChild(cell);
				}else if(column_name[k] === "Disc"){
					var input = document.createElement("input");
					input.classList.add(".disc", "input_no_border");
					input.setAttribute("min",0);
					input.setAttribute("max",100);
					input.value = 0.00;

					cell.appendChild(input);
					r.appendChild(cell);
				}else if(column_name[k] === "Unit Price"){
					var input = document.createElement("input");
					input.classList.add(".price","input_no_border");
					input.value = 0.00;

					cell.appendChild(input);
					r.appendChild(cell);
				}else if(column_name[k] === "Request Date"){
					var input = document.createElement("input");
					input.classList.add("rdate","input_no_border");
	
					cell.appendChild(input);
					r.appendChild(cell);
				}else{
					var input = document.createElement("input");
					input.className = "input_no_border"

					cell.appendChild(input);
					r.appendChild(cell);
				}
			}
		}
		
		t_body.appendChild(r);
	}

	table.appendChild(t_body);
	table.setAttribute("border","2");
	table.setAttribute("id",id_value);

	return table;			
}

var dropdown = null;
function clearDropdown() {
	if (dropdown) {
		dropdown.remove();
		dropdown = null;
	}
}

/*
 * The function check_input() was generated by GPT initially.
 * */

let orders_list;
let customers_list;
function check_input(){ 
	var cust = false;
	var s_ord = false;
	
	var input;
	var page = document.URL;
	if(page.includes('sales_orders')){
		input = document.getElementById("cust-id");		
		cust = true;
		if(input == null){
			cust = false;
			s_ord = true;
			input = document.getElementById("edit-cust-id");
		}
	}else if(page.includes('customers')){
		input = document.getElementById("cust-id");		
		cust = true;
	}

	const value = input.value;
	clearDropdown();

	if (!value) return;

	let matched;
	if(cust){
		matched = customers_list.filter((customer) => customer.toLowerCase().includes(value.toLowerCase()));
	}else if(s_ord){
		matched = orders_list.filter(order =>order.toString().includes(value)).slice(0, 20);
	}

	if (matched.length === 0) return;

	dropdown = document.createElement("div");
	dropdown.setAttribute("style", `
                position: absolute;
                background: white;
                border: 1px solid #ccc;
                max-height: 200px;
                overflow-y: auto;
                width: ${input.offsetWidth}px;
                z-index: 1000;
	`);

	const inputRect = input.getBoundingClientRect();
	dropdown.style.left = inputRect.left + window.scrollX + "px";
	dropdown.style.top = inputRect.bottom + window.scrollY + "px";

	if(s_ord){
		matched.forEach(order => {
			const option = document.createElement("div");
			option.textContent = order;
			option.setAttribute("style", `
			padding: 5px;
			cursor: pointer;
		`);
			option.addEventListener("mouseover", () => {
				option.style.backgroundColor = "#f0f0f0";
			});
			option.addEventListener("mouseout", () => {
				option.style.backgroundColor = "white";
			});

			option.addEventListener("click", async () => {
				input.value = order;
				clearDropdown();
				/*this fetch the order selected from the server*/
				let response = await send(null,"GET",`sales_orders/${order}`);

				console.log(`${JSON.stringify(response.message)}`);
				/*if there is a table already, destroy it and make a new one */
				/*create the order form populated with the order sales from the back end selected*/
				if(response.message == undefined){
					alert("error in receving json object");
					return;
				}else if(response.message === "there are no orders"){
					alert("there are no orders");
					return ;
				}			
				var d = document.getElementById("edit-order-menu");

				var br = document.createElement("br");
				d.appendChild(br);

				console.log(`${JSON.stringify(response.message)}`);
				var el = document.getElementById("cust-id");
				if(el != null){

					if(response.message.sales_orders_head.customer_id != undefined){
						el.value = response.message.sales_orders_head.customer_id;
					}else{
						el.value = "";
					}

					var price_lvl = document.getElementById("price-level");
					if(response.message.sales_orders_head.price_level != undefined){
						price_lvl.value = response.message.sales_orders_head.price_level;
					}else{
						price_lvl.value = "";
					}

					var date = document.getElementById("date");
					if(response.message.sales_orders_head.date != undefined){
						date.textContent = response.message.sales_orders_head.date;
					}

					var old_edit = document.getElementById("edit");
					old_edit.remove();

					var edit = document.createElement("button");
					edit.textContent = "Edit";
					edit.setAttribute("id","edit");
					edit.setAttribute("style","font-size:18px;margin-right:500px;");
					edit.addEventListener("click",function(event){
						submit_order("update",`${order}`,"edit-order-table");
					}); 
					d.insertBefore(edit,date);

					var tbl = document.getElementById("edit-order-table");
					var lines = Number(response.message.sales_orders_head.lines_nr);	

					if((tbl.rows.length -1) < lines){
						for(let i = 0;i < lines - (tbl.rows.length - 1) ; i++){
							add_line_to_order("edit-order-table");
						}
					}
					var rows = tbl.rows;



					for(let i = 1;i < lines + 1; i++){
						var access_line_name = `line_${i}`;


						Array.from(rows[i].children).forEach((cell,index)=>{
							if(index == 0){
								if(response.message.sales_orders_lines[access_line_name].item != undefined){
									cell.children[0].value = response.message
										.sales_orders_lines[access_line_name].item;
								}else{
									cell.children[0].value ="";

								}
							}
							if(index == 1){
								if(response.message.sales_orders_lines[access_line_name].uom != undefined){
									cell.children[0].value = response.message
										.sales_orders_lines[access_line_name].uom;
								}else{
									cell.children[0].value = "";
								}
							}
							Array.from(cell.children).forEach(child =>{
								if(child.classList.contains(".tot")) {
									child.textContent = response.message
										.sales_orders_lines[access_line_name].total;
								}
								if(child.classList.contains(".qty")) {
									child.value = response.message
										.sales_orders_lines[access_line_name].qty;
								}
								if(child.classList.contains(".disc")) {
									if(response.message
										.sales_orders_lines[access_line_name]
										.disc == undefined){
										child.value = 0.00;
									}else{
										child.value = response.message
											.sales_orders_lines[access_line_name].disc;
									}
								}

								if(child.classList.contains(".price")) {
									child.value = response.message
										.sales_orders_lines[access_line_name].unit_price;
								}

								if(child.classList.contains("rdate")) {
									child.value = response.message
										.sales_orders_lines[access_line_name].request_date;
								}

							});
						});

					}
					/* clean tbl*/
					for(let i = lines; i < rows.length; i++ ){
						if(i == lines){
							continue;
						}
						tbl.deleteRow(i);
					}
					return 
				}

				var c_label = document.createElement("label");
				c_label.textContent = "Customer id:";
				c_label.className = "label";
				d.appendChild(c_label);

				var input_customer = document.createElement("input");
				input_customer.className = "input_2px_border";
				input_customer.setAttribute("id","cust-id");
				if(response.message.sales_orders_head.customer_id != null){
					input_customer.value = response.message.sales_orders_head.customer_id;
				}

				d.appendChild(input_customer);


				var br1 = document.createElement("br");
				d.appendChild(br1);

				/*create price level input field*/	
				var price_label = document.createElement("label");
				price_label.textContent = "Price level:";
				price_label.className = "label";
				d.appendChild(price_label);

				var price_level= document.createElement("input");
				price_level.className = "input_2px_border";
				price_level.setAttribute("id","price-level");

				if(response.message.sales_orders_head.price_level != null){
					price_level.value = response.message.sales_orders_head.price_level;
				}

				d.appendChild(price_level);

				var add_line = document.createElement("button");
				add_line.textContent = "Add line";
				add_line.setAttribute("id","add_line");
				add_line.setAttribute("style","font-size:18px;margin-rigth:18px;");
				add_line.addEventListener("click", function(event){
					add_line_to_order("edit-order-table");
				});
				d.appendChild(add_line);

				var edit = document.createElement("button");
				edit.textContent = "Edit";
				edit.setAttribute("id","edit");
				edit.className = "button";
				edit.addEventListener("click",function(event){
					submit_order("update",`${order}`,"edit-order-table");
				}); 
				d.appendChild(edit);

				var date = document.createElement("label");
				date.setAttribute("id","date");
				date.setAttribute("style","font-size:24px;");
				date.textContent = response.message.sales_orders_head.date;	
				d.appendChild(date);

				/*create table and populate with the response */		
				d.appendChild(create_table(response.message.sales_orders_head.lines_nr,
					["Item","Uom","Qty","Disc","Unit Price","Total","Request Date"],"edit-order-table"));

				var order_total_desc = document.createElement("label");
				order_total_desc.textContent = "Order Total: $";
				order_total_desc.setAttribute("style","font-size:24px;margin-right:15px;");
				var order_total_label= document.createElement("label");
				order_total_label.setAttribute("style","font-size:24px;");
				order_total_label.setAttribute("id","order-total-lbl");

				const d_child_one = document.createElement(element.div.type);
				d_child_one.setAttribute("id","order-total");
				d_child_one.setAttribute("style","margin-left:64%;");
				d_child_one.appendChild(order_total_desc);
				d_child_one.appendChild(order_total_label);
				d.appendChild(d_child_one);


				/*add event to populate the total, int the table*/
				document.getElementById("edit-order-table").addEventListener('change',compute_total);

				/* populate the table with the order lines*/
				var tbl = document.getElementById("edit-order-table");
				var rows = tbl.rows;
				if((rows.length - 1) < Number(response.message.sales_orders_head.lines_nr)){
					for(let i = 0; i < Number(response.message.sales_orders_head.lines_nr) - (rows.length-1);i++){
						add_line_to_order("edit-order-table");		
					}
				}
				var sum = 0;
				for(let i = 1;i < Number(response.message.sales_orders_head.lines_nr) + 1; i++){

					var access_line_name = `line_${i}`;
					Array.from(rows[i].children).forEach((cell,index)=>{
						if(index == 0){
							if(response.message.sales_orders_lines[access_line_name].item != undefined){
								cell.children[0].value = response.message
									.sales_orders_lines[access_line_name].item;
							}
						}
						if(index == 1){
							if(response.message.sales_orders_lines[access_line_name].uom != undefined){
								cell.children[0].value = response.message
									.sales_orders_lines[access_line_name].uom;
							}
						}
						Array.from(cell.children).forEach(child =>{
							if(child.classList.contains(".qty")) {
								child.value = response.message.sales_orders_lines[access_line_name].qty;
							}

							if(child.classList.contains(".disc")) {
								if(response.message
									.sales_orders_lines[access_line_name]
									.disc == undefined){
									child.value = 0.00;
								}else{
									child.value = response.
										message.
										sales_orders_lines[access_line_name].disc;
								}
							}
							if(child.classList.contains(".tot")){
								if(response.message
									.sales_orders_lines[access_line_name]
									.total == undefined){
									child.value = 0.00;
									sum += Number(child.textContent);
								}else{
									child.textContent = `$ ${response.message.sales_orders_lines[access_line_name].total}`;
									sum += Number(response.message.sales_orders_lines[access_line_name].total);
								}
							}
							if(child.classList.contains(".price")) {
								child.value = response.message.sales_orders_lines[access_line_name].unit_price;
							}

							if(child.classList.contains("rdate")) {
								child.value = response.message.sales_orders_lines[access_line_name].request_date;
							}
						});
					});
				}
				order_total_label.textContent = sum;
			});
			dropdown.appendChild(option);
		});
	}else if(cust){
		matched.forEach(customer => {
			const option = document.createElement("div");
			option.textContent = customer;
			option.setAttribute("style", `
			padding: 5px;
			cursor: pointer;
		`);
			option.addEventListener("mouseover", () => {
				option.style.backgroundColor = "#f0f0f0";
			});
			option.addEventListener("mouseout", () => {
				option.style.backgroundColor = "white";
			});

			option.addEventListener("click",async () =>{
				input.value =customer;
				clearDropdown();
				/*this fetch customer info, like pay_price level, discounts, and 
				 * possible restrictions like credit hold, selected  */
				let response = await send(null,"GET",`customers/${customer}`);
				if(response.message.on_credit_hold != undefined){
					if(response.message.on_credit_hold == 1){
							alert("client is on credit hold, see your manager");
							clear_order_screen();
							return;
					}
				}
			});
			dropdown.appendChild(option);
		});
	}
	document.body.appendChild(dropdown);

	// Close dropdown if clicking outside
	document.addEventListener("click", (e) => {
		if (e.target !== input) clearDropdown();
	});
}

async function get_orders(){
	const response = await send(null,"GET","sales_orders");	
	if(response.message.includes("there are no orders")){
		alert(response.message);		
		clear_order_screen();
		return;
	}
	orders_list = response.message;


	var input = document.getElementById("edit-cust-id");
	input.removeEventListener("focus",get_orders);
	input.addEventListener("input",check_input);
}


async function get_customers(){
	const response = await send(null,"GET","customers");	
	customers_list = response.message;

	console.log(customers_list);
	var input = document.getElementById("cust-id");
	input.removeEventListener("focus",get_customers);
	input.addEventListener("input",check_input);
}

function render_edit_order(){
	var btn = document.getElementById("edit-order");
	btn.textContent = "Back";
	btn.setAttribute("id","back");
	btn.removeEventListener("click",render_edit_order);
	btn.addEventListener("click",clear_order_screen);

	var btn2 = document.getElementById("new-order");
	btn2.style.display = "none";

	const d = document.createElement(element.div.type);
	d.setAttribute("id","edit-order-menu");
	d.setAttribute("class","main");
	d.setAttribute("style","margin-top:15px;");

	/*create order nr input fields*/
	var o_label = document.createElement("label");
	o_label.textContent = "Order number:";
	o_label.className = "label";
	d.appendChild(o_label);

	var input_order = document.createElement("input");
	input_order.addEventListener("focus",get_orders);
	input_order.className = "input_2px_border";
	input_order.setAttribute("id","edit-cust-id");
	d.appendChild(input_order);

	document.body.appendChild(d);

}

function show_tax_authority()
{
	var ch_b = document.getElementById('tax');
	if(ch_b.checked == true){
		var tax_aut_lbl = document.createElement("label");
		tax_aut_lbl.textContent = "Tax Authority";
		tax_aut_lbl.classList.add("label");
		tax_aut_lbl.setAttribute("id","tax-lbl");
		var tax_aut_input = document.createElement("input");
		tax_aut_input.classList.add("input_2px_border");
		tax_aut_input.setAttribute("id","tax-input");
		tax_aut_input.setAttribute("autocomplete","off");
		ch_b.after(tax_aut_lbl);
		tax_aut_lbl.after(tax_aut_input);
	}else{
		var tax_aut = document.getElementById("tax-input");
		if(tax_aut){
			var lbl = document.getElementById("tax-lbl");
			lbl.remove();
			tax_aut.remove();
		}
	}
}

function render_new_customer(){

	/*get the root div*/
	var root = document.getElementById("root-new-customer");
	if(root){
		/*clear screen*/
		root.remove();
		location.reload();
		return;		
	}

	const sb_btn = document.createElement("button");
	sb_btn.addEventListener("click",submit_new_customer);
	sb_btn.classList.add("button");
	sb_btn.textContent = "Save Customer";

	const nw_cust_btn = document.getElementById("new-cust");
	nw_cust_btn.textContent = "Back";
	const edit_cust_btn = document.getElementById("edit-cust");
	edit_cust_btn.remove();

	const d = document.createElement("div");
	d.setAttribute("id","root-new-customer");
	d.setAttribute("style","margin-top:15px;");
	d.classList.add("main");

	/*create layout customer*/
	var c_name_lbl = document.createElement("label");
	c_name_lbl.textContent = "Customer Name: ";

	var c_name_input = document.createElement("input");
	c_name_input.classList.add("input_2px_border");
	c_name_input.setAttribute("id","new-customer-name");

	var c_hdq_id_lbl = document.createElement("label");
	c_hdq_id_lbl.textContent = "Customer Head quorter Id";
	var c_hdq_id_input = document.createElement("input");
	c_hdq_id_input.classList.add("input_2px_border");
	c_hdq_id_input.setAttribute("id","cust-id");
	c_hdq_id_input.title = "use an existing customer if this is just another shipping address";

	c_hdq_id_input.addEventListener("focus",get_customers); /*same as customer id*/
	
	
	var sls_person_lbl = document.createElement("label");
	sls_person_lbl.textContent = "Sales person id:";
	sls_person_lbl.classList.add("label");
	var sls_person_input = document.createElement("input");
	sls_person_input.classList.add("input_2px_border");	
	sls_person_input.setAttribute("id","sls-person");
	sls_person_input.setAttribute("autocomplete","off");

	var main_pr_level_lbl = document.createElement("label");
	main_pr_level_lbl.textContent = "Main Price Level:";
	main_pr_level_lbl.classList.add("label");
	var main_pr_level_input = document.createElement("input");
	main_pr_level_input.classList.add("input_2px_border");	
	main_pr_level_input.setAttribute("id","main-pr-level");
	main_pr_level_input.setAttribute("autocomplete","off");
	main_pr_level_input.title = "If you have configured Price levels " + 
								"you can choose one value, if you want to have a customer" + 
								" that always has a certain type of discount.";

	var address_lbl = document.createElement("label");
	address_lbl.classList.add("label","desc");
	address_lbl.textContent = "Customer Address:";

	var addr1_lbl = document.createElement("label");
	addr1_lbl.textContent = "Street:";
	addr1_lbl.classList.add("label");
	var addr1_input = document.createElement("input");
	addr1_input.classList.add("input_2px_border");	
	addr1_input.setAttribute("id","addr1");
	addr1_input.setAttribute("autocomplete","off");


	var addr2_lbl = document.createElement("label");
	addr2_lbl.textContent = "Additional Address info:";
	addr2_lbl.classList.add("label");
	var addr2_input = document.createElement("input");
	addr2_input.placeholder = "Optional";
	addr2_input.classList.add("input_2px_border");
	addr2_input.setAttribute("id","addr2");
	addr2_input.setAttribute("autocomplete","off");

	var city_lbl = document.createElement("label");
	city_lbl.textContent = "City: ";
	var city_input = document.createElement("input");
	city_input.setAttribute("id","city");
	city_input.classList.add("input_2px_border");
	city_input.setAttribute("autocomplete","off");

	var state_lbl = document.createElement("label");
	state_lbl.textContent = "State: ";
	var state_input = document.createElement("input");
	state_input.setAttribute("id","state");
	state_input.classList.add("input_2px_border");
	state_input.setAttribute("autocomplete","off");

	var zipcode_lbl = document.createElement("label");
	zipcode_lbl.textContent = "Zip code:";
	zipcode_lbl.classList.add("label");	
	var zipcode_input = document.createElement("input");
	zipcode_input.setAttribute("id","zipcode");
	zipcode_input.classList.add("input_2px_border");
	zipcode_input.setAttribute("autocomplete","off");

	var country_lbl = document.createElement("label");
	country_lbl.textContent = "Country:";
	country_lbl.classList.add("label");	
	var country_input = document.createElement("input");
	country_input.setAttribute("id","country");
	country_input.classList.add("input_2px_border");
	country_input.setAttribute("autocomplete","off");

	var phone_lbl = document.createElement("label");
	phone_lbl.classList.add("label");
	phone_lbl.textContent = "Phone:";
	var phone_input = document.createElement("input");
	phone_input.setAttribute("id","phone");
	phone_input.classList.add("input_2px_border");
	phone_input.setAttribute("autocomplete","off");

	var contat_lbl = document.createElement("label");
	contat_lbl.classList.add("label");
	contat_lbl.textContent = "Contact Person:";
	var contat_input = document.createElement("input");
	contat_input.setAttribute("id","contact");
	contat_input.classList.add("input_2px_border");
	contat_input.setAttribute("autocomplete","off");

	var email_lbl = document.createElement("label");
	email_lbl.classList.add("label");
	email_lbl.textContent = "Email:";
	var email_input = document.createElement("input");
	email_input.setAttribute("id","email");
	email_input.classList.add("input_2px_border");
	email_input.setAttribute("autocomplete","off");

	var is_tax_exempt_lbl = document.createElement("label");
	is_tax_exempt_lbl.classList.add("label");
	is_tax_exempt_lbl.textContent = "is tax exempt?";
	var checkbox = document.createElement("input");
	checkbox.setAttribute("id","tax");
	checkbox.setAttribute("type","checkbox");
	checkbox.addEventListener("click",show_tax_authority);	
	checkbox.classList.add("chkbox");
	

	var warehouse_lbl = document.createElement("label");
	warehouse_lbl.classList.add("label");
	warehouse_lbl.textContent = "Warehouse: ";
	var warehouse_input = document.createElement("input");
	warehouse_input.setAttribute("id","warehouse");
	warehouse_input.classList.add("input_2px_border");
	warehouse_input.setAttribute("autocomplete","off");

	var sales_term_lbl = document.createElement("label");
	sales_term_lbl.classList.add("label");
	sales_term_lbl.textContent = "Sale terms: ";
	var sales_term_input = document.createElement("input");
	sales_term_input.setAttribute("id","sale-term");
	sales_term_input.classList.add("input_2px_border");
	sales_term_input.setAttribute("autocomplete","off");

	var credit_limit_lbl = document.createElement("label");
	credit_limit_lbl.classList.add("label");
	credit_limit_lbl.textContent = "Credit Limit: ";
	var credit_limit_input= document.createElement("input");
	credit_limit_input.setAttribute("id","credit-limit");
	credit_limit_input.classList.add("input_2px_border");
	credit_limit_input.setAttribute("autocomplete","off");

	/*spaces in the page*/
	var space1 = document.createElement("div");
	space1.classList.add("space");
	var space2 = document.createElement("div");
	space2.classList.add("space");
	var space3 = document.createElement("div");
	space3.classList.add("space");
	var space4 = document.createElement("div");
	space4.classList.add("space");
	var space5 = document.createElement("div");
	space5.classList.add("space");
	var space6 = document.createElement("div");
	space6.classList.add("space");
	var space7 = document.createElement("div");
	space7.classList.add("space");

	/*breaks in the page*/
	var br1 = document.createElement("br");
	var br2 = document.createElement("br");
	var br3 = document.createElement("br");
	var br4 = document.createElement("br");
	var br5 = document.createElement("br");
	var br6 = document.createElement("br");
	var br7 = document.createElement("br");
	var br8 = document.createElement("br");
	var br9 = document.createElement("br");
	var br10 = document.createElement("br");
	var br11 = document.createElement("br");
	var br12 = document.createElement("br");

	var style_break1 = document.createElement("hr");
	var style_break2 = document.createElement("hr");
	var style_break3 = document.createElement("hr");
	var style_break4 = document.createElement("hr");
	var style_break5 = document.createElement("hr");

	d.appendChild(c_name_lbl);
	d.appendChild(c_name_input);
	d.appendChild(c_hdq_id_lbl);
	d.appendChild(c_hdq_id_input);
	d.appendChild(br1);
	d.appendChild(sls_person_lbl);
	d.appendChild(sls_person_input);
	d.appendChild(main_pr_level_lbl);
	d.appendChild(main_pr_level_input);
	d.appendChild(style_break1);
	d.appendChild(br3);
	d.appendChild(address_lbl);
	d.appendChild(space1);
	d.appendChild(br4);
	d.appendChild(addr1_lbl);
	d.appendChild(addr1_input);
	d.appendChild(addr2_lbl);
	d.appendChild(addr2_input);
	d.appendChild(space2);
	d.appendChild(br5);
	d.appendChild(city_lbl);
	d.appendChild(city_input);
	d.appendChild(zipcode_lbl);
	d.appendChild(zipcode_input);
	d.appendChild(state_lbl);
	d.appendChild(state_input);
	d.appendChild(country_lbl);
	d.appendChild(country_input);
	d.appendChild(style_break2);
	d.appendChild(space3);
	d.appendChild(br6);
	d.appendChild(contat_lbl);
	d.appendChild(contat_input);
	d.appendChild(phone_lbl);
	d.appendChild(phone_input);
	d.appendChild(email_lbl);
	d.appendChild(email_input);
	d.appendChild(space4);
	d.appendChild(br7);
	d.appendChild(is_tax_exempt_lbl);
	d.appendChild(checkbox);
	d.appendChild(style_break3);
	d.appendChild(space5);
	d.appendChild(br8);
	d.appendChild(warehouse_lbl);
	d.appendChild(warehouse_input);
	d.appendChild(sales_term_lbl);
	d.appendChild(sales_term_input);
	d.appendChild(credit_limit_lbl);
	d.appendChild(credit_limit_input);
	d.appendChild(space5);
	d.appendChild(br8);
	d.appendChild(sb_btn);
	document.body.appendChild(d);
}

function render_edit_cusromer(){}
function render_new_order(){

	var root = document.getElementById("new-order-menu");
	if(root){
		root.remove();
		location.reload();
		return;
	}

	const d = document.createElement(element.div.type);
	d.setAttribute("id","new-order-menu");
	d.setAttribute("style","margin-top:15px;");
	d.setAttribute("class","main");

	/*create custumer input fields*/
	var c_label = document.createElement("label");
	c_label.textContent = "Customer id:";
	c_label.className = "label";
	d.appendChild(c_label);

	var input_customer = document.createElement("input");
	input_customer.className = "input_2px_border";
	input_customer.setAttribute("id","cust-id");
	input_customer.setAttribute("title","Customer identification in the system");
	input_customer.addEventListener("focus",get_customers);
	d.appendChild(input_customer);

	var br = document.createElement("br");
	d.appendChild(br);

	/*create price level input field*/	
	var price_label = document.createElement("label");
	price_label.textContent = "Price level:";
	price_label.className = "label";
	d.appendChild(price_label);

	var price_level= document.createElement("input");
	price_level.className = "input_2px_border";
	price_level.setAttribute("id","price-level");
	d.appendChild(price_level);

	var add_line = document.createElement("button");
	add_line.textContent = "Add line";
	add_line.setAttribute("id","add_line");
	add_line.setAttribute("style","font-size:18px;margin-rigth:18px;");
	add_line.addEventListener("click",function(event){
		add_line_to_order("new-order-table");
	});

	d.appendChild(add_line);

	var submit = document.createElement("button");
	submit.textContent = "Submit";
	submit.setAttribute("id","submit");
	submit.setAttribute("style","font-size:18px;margin-right:500px;");
	submit.addEventListener("click",function(event){
		submit_order("new",0,"new-order-table");
	});
	d.appendChild(submit);

	var date = document.createElement("label");
	date.setAttribute("id","date");
	date.setAttribute("style","font-size:24px;");
	var today = new Date();
	var day = today.getDate();
	var month = today.getMonth() +1;
	var year = today.getFullYear();
	if(month < 10) month = '0' + month;
	if(day < 10) day = '0' + day;
	date.textContent = `${month}-${day}-${year}`;	
	d.appendChild(date);


	/*create the table to insert the orders*/
	d.appendChild(create_table(1,["Item","Uom","Qty","Disc","Unit Price","Total","Request Date"],"new-order-table"));
	var br2 = document.createElement("br");
	d.appendChild(br2);

	var order_total_desc = document.createElement("label");
	order_total_desc.textContent = "Order Total: $";
	order_total_desc.setAttribute("style","font-size:24px;margin-right:15px;");
	var order_total_label= document.createElement("label");
	order_total_label.setAttribute("style","font-size:24px;");
	order_total_label.setAttribute("id","order-total-lbl");

	const d_child_one = document.createElement(element.div.type);
	d_child_one.setAttribute("id","order-total");
	d_child_one.setAttribute("style","margin-left:64%;");
	d_child_one.appendChild(order_total_desc);
	d_child_one.appendChild(order_total_label);
	d.appendChild(d_child_one);

	document.body.appendChild(d);
	document.getElementById("new-order-table").addEventListener('change',compute_total);

	var btn = document.getElementById("new-order");
	btn.textContent = "Back";
	btn.setAttribute("id","back");
	btn.removeEventListener("click",render_new_order);
	btn.addEventListener("click",clear_order_screen);

	var btn2 = document.getElementById("edit-order");
	btn2.style.display = "none";
}

function compute_total(event) {
	// Check if the event target is an input field within a table row
	if (!(event.target instanceof HTMLInputElement)) return; 

	const current_row = event.target.closest('tr');
	if(!current_row) return;

	let lbl = null;
	let qty_el = null;
	let price_el = null;
	let disc_el = null;

	Array.from(current_row.children).forEach(child =>{
		if(child.firstChild.classList.contains(".tot")) lbl = child.firstChild;
		if(child.firstChild.classList.contains(".qty")) qty_el = child.firstChild;
		if(child.firstChild.classList.contains(".price")) price_el = child.firstChild;
		if(child.firstChild.classList.contains(".disc")) disc_el = child.firstChild;
	});

	if(!qty_el || !price_el || !lbl) return;

	var qty = parseFloat(qty_el.value).toFixed(2);
	var disc = parseFloat(disc_el.value).toFixed(2);
	var price = parseFloat(price_el.value).toFixed(2);

	if(disc == 0.00 || isNaN(disc) || disc < 0){
		lbl.textContent = `$ ${qty * price}`;
	}else{
		var tot = parseFloat((qty * price) - (((qty*price)* disc ) /100)).toFixed(2);
		lbl.textContent = `$ ${tot}`;
	}


	var tbl = document.getElementById("new-order-table");
	if(tbl == null){
		tbl = document.getElementById("edit-order-table");
	}
	var rows = tbl.rows;
	let sum = parseFloat("0.00");
	for(let i = 1;i < rows.length; i++){
		if(rows[i].style.display === "none") break;

		Array.from(rows[i].children).forEach((cell,index)=>{
			Array.from(cell.children).forEach(child =>{
				if(child.textContent !== "") {
					if(child.textContent === "0"){
						sum = parseFloat(sum) + parseFloat(child.textContent);
					}else{
						let strs = child.textContent.split(" ");
						sum = parseFloat(sum) + parseFloat(strs[1]);
					}
				}
			});
		});
	}

	var tot_lbl = document.getElementById("order-total-lbl");
	if(tot_lbl.textContent === "")
		tot_lbl.textContent = sum !== "Nan" ? `${sum.toFixed(2)}` : `${0.00}`;
	else 
		tot_lbl.textContent = sum !== "Nan" ? `${sum.toFixed(2)}` : `${tot_lbl.textContent}`;

}


function add_line_to_order(table_id){
	var table = document.getElementById(table_id);

	var row = table.insertRow(-1);
	for(let i = 0; i < table.rows[0].cells.length; i++){
		var cell = document.createElement("td");		
		cell.setAttribute("width","200");
		cell.setAttribute("style","padding:0;");

		if(table.rows[0].cells[i].textContent === "Total"){
			var tot = document.createElement("label");				
			tot.setAttribute("style","width:100%;height:100%;box-sizing:border-box;font-size:24px;");
			tot.classList.add(".tot");
			cell.appendChild(tot);
		}else if( table.rows[0].cells[i].textContent === "Qty"){
			var input = document.createElement("input");
			input.classList.add(".qty","input_no_border");
			input.value = 0.00;

			cell.appendChild(input);
		}else if(table.rows[0].cells[i].textContent  === "Disc"){
			var input = document.createElement("input");
			input.classList.add(".disc","input_no_border");
			input.value = 0.00;

			cell.appendChild(input);
		}else if(table.rows[0].cells[i].textContent  === "Unit Price"){
			var input = document.createElement("input");
			input.classList.add(".price","input_no_border");
			input.value = 0.00;

			cell.appendChild(input);
		}else if(table.rows[0].cells[i].textContent === "Request Date"){
			var input = document.createElement("input");
			input.classList.add("rdate","input_no_border");

			cell.appendChild(input);
		}else{
			var input = document.createElement("input");
			input.className = "input_no_border";

			cell.appendChild(input);
		}
		row.appendChild(cell);
	}
}

function clear_order_screen(event){

	var main_p = document.getElementById("root");
	var root = document.getElementById("new-order-menu");
	if(root == null){
		root = document.getElementById("edit-order-menu");
	}
	if(event === undefined){
		root.remove();
		location.reload();
		/*
		var btn = document.getElementById("back");
		if(root.id === "root"){
			btn.textContent ="New Order";
			btn.setAttribute("id", "new-order");
			btn.removeEventListener("click",clear_order_screen);
			btn.addEventListener("click",render_new_order);
			var btn2 = document.getElementById("edit-order");
			btn2.style.display = null;
		}else if(root.id === "edit-order-menu"){
			var btn = document.getElementById("back");
			btn.textContent ="Edit Order";
			btn.setAttribute("id", "edit-order");
			btn.removeEventListener("click",clear_order_screen);
			btn.addEventListener("click",render_edit_order);
			var btn2 = document.getElementById("new-order");
			btn2.style.display = null;
		}
		*/

		return;
	}else if(event.type === 'click'){
		
		let result;
		if(document.getElementById("cust-id") != null){
			/*look for all the elements*/
			var cust_input = document.getElementById("cust-id");
			var price_input = document.getElementById("price-level");
			var tbl_qtys = document.getElementsByClassName(".qty");
			var tbl_totals = document.getElementsByClassName(".tot");
			var tbl_discs = document.getElementsByClassName(".disc");
			var tbl_prices = document.getElementsByClassName(".price");
			
			var ask = false;
			for(let i = 0; i < tbl_qtys.length;i++){
				if(tbl_qtys[i].value != 0) ask = true;
			}
			if(!ask){
				for(let i = 0; i < tbl_totals.length;i++){
					if(tbl_totals[i].textContent !== '') ask = true;
				}
			}
			if(!ask){
				for(let i = 0; i < tbl_discs.length;i++){
					if(tbl_discs[i].value != 0) ask = true;
				}
			}

			if(!ask){
				for(let i = 0; i < tbl_prices.length;i++){
					if(tbl_prices[i].value != 0) ask = true;
				}
			}

			if(ask){
				result = prompt("Do you want to save the order?");
			}
		}

		if(!result){
			var root = document.getElementById("new-order-menu");
			if(root == null){
				root = document.getElementById("edit-order-menu");
			}
			root.remove();
			location.reload();
			/*
			var btn = document.getElementById("back");
			if(root.id === "new-oreder-menu"){
				btn.textContent ="New Order";
				btn.setAttribute("id", "new-order");
				btn.removeEventListener("click",clear_order_screen);
				btn.addEventListener("click",render_new_order);
				var btn2 = document.getElementById("edit-order");
				btn2.style.display = null;
			}else if(root.id === "edit-order-menu"){
				btn.textContent ="Edit Order";
				btn.setAttribute("id", "edit-order");
				btn.removeEventListener("click",clear_order_screen);
				btn.addEventListener("click",render_edit_order);
				var btn2 = document.getElementById("new-order");
				btn2.style.display = null;
			}
			*/
			return;
		}else if(result.toLowerCase() === "yes" || result.toLowerCase() === "y"){
			if(root.id === "new-order-menu"){
				alert("order saved!");
				var root = document.getElementById(root.id);
				root.setAttribute("style","display:'false';");
				var btn = document.getElementById("back");
				btn.textContent ="New Order";
				btn.setAttribute("id", "new-order");
				btn.removeEventListener("click",clear_order_screen);
				btn.addEventListener("click",render_new_order);
				var btn2 = document.getElementById("edit-order");
				btn2.style.display = null;
				return;
			}else if(root.id === "edit-order-menu"){
				alert("changed saved!");
				var root = document.getElementById("edit-order-menu");
				root.setAttribute("style","display:none;");
				var btn = document.getElementById("back");
				btn.textContent = "Edit Order";
				btn.setAttribute("id", "edit-order");
				btn.removeEventListener("click",clear_order_screen);
				btn.addEventListener("click",render_edit_order);
				var btn2 = document.getElementById("new-order");
				btn2.style.display = null;
				return;
			}
			return;
		}
	}
}

function remove_null_values(obj){
	return Object.fromEntries(
		Object.entries(obj).filter(([_,v])=> v !== null)
	);
}

function get_table_data(table_id){
	const table = document.getElementById(table_id);
	const headers = Array.from(table.querySelectorAll("th")).map(th => th.textContent.trim());

	let rows = table.rows;
	let data = [];
	let error = false;
	for(let i = 1; i < rows.length; i++){
		let row_obj = {};
		Array.from(rows[i].children).forEach((cell, index) =>{
			Array.from(cell.children).forEach(child =>{
				if(child.value !== "" && child.value !== "0" && child.value != undefined){
					if(child.classList.contains(".qty") 	|| 
						child.classList.contains(".tot") 	||
						child.classList.contains(".price") 	|| 
						child.classList.contains(".disc") 	){

						if(isNaN(Number(child.value))){
							error = true;
						}
					}
					row_obj[headers[index].toLowerCase().replace(" ","_")] = child.value;
				}

				if(child.textContent !== ""){
					var n = child.textContent.split(" ");
					row_obj[headers[index].toLowerCase()] = n[1];
				}
			});
		});

		if(Object.keys(row_obj).length > 0){
			data.push(row_obj);	
		}
	}


	if(error){
		data = null;
	}
	return data;
}

async function submit_order(crud_op,value,from_table){
	const cust_id = document.getElementById("cust-id");
	const price_level = document.getElementById("price-level");
	const date = document.getElementById("date");

	let lines = get_table_data(from_table);

	if(lines == null){
		alert("check the input, one or more fields have inllegal values")
		return;
	}
	if(Object.keys(lines).length == 0){
		if(crud_op == "new"){
			alert("cannot add an empty order");
		}else{

			alert("cannot update this order, do you want to delete it?");
		}

		return;
	}

	//console.log(Array.isArray(lines));
	//console.log(lines.length);
	
	let lines_count = lines.length;
	let orders_header = remove_null_values({
		date: date.textContent === "" ? null : date.textContent,
		customer_id: cust_id.value === "" ? null : cust_id.value,
		price_level: price_level.value === "" ? null : price_level.value,
		lines_nr : `${lines_count}` 
	});

	let payload = {
		sales_orders_head: orders_header,
		sales_orders_lines: lines 
	};

	const json_payload = JSON.stringify(payload);
	if(crud_op === "new"){
		console.log(json_payload);
		const response = await send(json_payload,"POST","new_sales_order");
		alert(`${response.message}`);
		//clear_order_screen();
	}else if (crud_op === "update"){
		console.log(json_payload);
		const response = await send(json_payload,"POST",`update_orders/sales/${value}`);
		alert(`${response.message}`);
		clear_order_screen();
	}
}


function submit_new_customer(){
	var inputs = document.querySelectorAll("input");

	var cust_payload;
	var cust_name = "";
	var cust_country = "";
	var cust_id = "";
	var cust_addr1 = "";
	var cust_addr2= "";
	var cust_csz= "";
	var cust_contact= "";
	var cust_email= "";
	var cust_phone= "";
	var cust_tax= "";
	var cust_warehouse= "";
	var cust_terms= "";
	var cust_credit_limit= "";
	inputs.forEach((input) =>{
		if(input.id === "new-customer-name") cust_name = input.value;
		if(input.id === "cust-id") cust_id = input.value;
		if(input.id === "addr1") cust_addr1 = input.value;
		if(input.id === "addr2") cust_addr2= input.value;
		if(input.id === "city") cust_csz +=  input.value + " " ;
		if(input.id === "state") cust_csz +=  input.value + " " ;
		if(input.id === "zipcode") cust_csz +=  input.value + " ";
		if(input.id === "country") cust_country = input.value;
		if(input.id === "contact") cust_contact = input.value;
		if(input.id === "email") cust_email = input.value;
		if(input.id === "phone") cust_phone = input.value;
		if(input.id === "chkbox"){
			cust_tax = input.value;
		}
		if(input.id === "warehouse") cust_warehouse = input.value;
		if(input.id === "sale-term") cust_terms = input.value;
		if(input.id === "credit-limit") cust_credit_limit = input.value;
	});

	cust_payload = remove_null_values({
		c_name: cust_name === "" ? null : cust_name,
		c_addr: cust_addr1 === "" ? null : cust_addr1,
		c_csz: cust_csz === "" ? null : cust_csz,
		c_email: cust_email === "" ? null : cust_email,
		c_phone: cust_phone === "" ? null : cust_phone,
		c_terms: cust_terms === "" ? null : cust_terms,
		c_limits: cust_credit_limit === "" ? null : cust_credit_limit,
		c_limits: cust_credit_limit === "" ? null : cust_credit_limit,
		c_whse_number: cust_warehouse === "" ? null : cust_warehouse
	});

	console.log(cust_payload);	
}
