#!/bin/bash

curl -v http://artech:8080/script.js \
  -H "Host: artech:8080" \
  -H "Upgrade-Insecure-Requests: 1" \
  -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
  -H "Accept-Language: en-US,en;q=0.9" \
  -H "Priority: u=0, i" \
  -H "Accept-Encoding: gzip, deflate" \
  -H "Connection: keep-alive"

