#!/bin/bash

for i in {1..10000}; do
	curl http://artech:8080
	curl http://artech:8080/style.css
	curl http://artech:8080/customers.html
	curl http://artech:8080/srcipt.js
	curl http://artech:8080/net.js
	curl http://artech:8080/sales_orders.js
	curl http://artech:8080/sales_orders.html
	curl http://artech:8080/etc/passwd
	curl http://artech:8080/root/
	curl http://artech:8080/proc
done

